version: '2'
services:
  sniproxy:
    image: mibatt/sniproxy:latest
    build: .
    hostname: sniproxy
    volumes:
      - "./sniproxy.conf:/etc/sniproxy.conf"
    ports:
      - "443:443" 
    command: /usr/sbin/sniproxy -c /etc/sniproxy.conf -f -n 65532
